title: Leanamycs
description: Lean 4 formalizations of opinion dynamics and related distributed processes
baseurl: "/leanamycs"
url: "https://leanamycs.github.io"
twitter_username:
github_username: leanamycs
repository: leanamycs/Leanamycs

authors: Aakash Kumar, Maria Sofia Bucarelli and Emanuele Natale

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
